# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019889e40fa65b4de98cd4ef1740bb9ff6e062d20f2661627119c679ea9f7f5da9da5cc8c99b4f41be940193c5b4964dd819e6407bd0a13d10ba698cac462b74

test:
  secret_key_base: 0f83276c033e43f4bf30651e12284fa710bcf3a0ef02337e02315d3df6bb5fea99cb3675fa240db3cec96b626c098e8ceffba5414eeba0e9a451735d38b35eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
